# Generated by Django 5.1.6 on 2025-02-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('mac_huaweii', models.CharField(blank=True, max_length=200, null=True)),
                ('port', models.CharField(blank=True, max_length=200, null=True)),
                ('localidade', models.CharField(blank=True, max_length=200, null=True)),
                ('switch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('up_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arp',
            },
        ),
    ]
